# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nathanlapre
email: nathan@nathanlapre.com
description: > # this means to ignore newlines until "baseurl:"
  Nathan LaPre
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nathanlapre.com" # the base hostname & protocol for your site
twitter_username: nathanlapre
github_username:  nmlapre

# Build settings
markdown: kramdown

#other settings
#pagination: 5
#paginate_path: "/blog/page:num/"
#gems: [jekyll-paginate]
